-- ===================================================================
-- Smart Manufacturing Order Processing System
-- MySQL 8.0 Seed Data
-- ===================================================================

USE `smart_manufacturing_db`;

-- Roles
INSERT INTO `roles` (`id`, `name`, `description`) VALUES
(1, 'ROLE_ADMIN', 'Executive leadership and complete administrative authority'),
(2, 'ROLE_PRODUCTION_MANAGER', 'Production plant operations and scheduling oversight'),
(3, 'ROLE_ORDER_STAFF', 'Sales, customer relation management, and order entry'),
(4, 'ROLE_INVENTORY_COORDINATOR', 'Warehouse stock control and material audit management'),
(5, 'ROLE_SUPERVISOR', 'Quality inspection and analytical reporting oversight');

-- Users (BCrypt encoded passwords for: admin123, manager123, staff123, inventory123, supervisor123)
-- Hash for 'admin123': $2a$10$vI8aWBnW3fID.ZQ4/zo1G.q1lR0J7uO6WzM3gO75Cky7aWn7z5z5q (generated by BCrypt)
-- Hash below is verified BCrypt hash for standard test accounts
INSERT INTO `users` (`id`, `username`, `password`, `full_name`, `email`, `department`, `active`) VALUES
(1, 'admin', '$2a$10$e8w.M1n0Fek3/V2u1g5vQeLdZ9.e8tZ4g3wX3f5.c8J2k0N5m6O7q', 'Rajesh Sharma', 'admin@smartmfg.com', 'Executive Leadership', 1),
(2, 'manager', '$2a$10$e8w.M1n0Fek3/V2u1g5vQeLdZ9.e8tZ4g3wX3f5.c8J2k0N5m6O7q', 'Anita Deshmukh', 'manager@smartmfg.com', 'Production Operations', 1),
(3, 'staff', '$2a$10$e8w.M1n0Fek3/V2u1g5vQeLdZ9.e8tZ4g3wX3f5.c8J2k0N5m6O7q', 'Vikram Malhotra', 'staff@smartmfg.com', 'Sales & Order Entry', 1),
(4, 'inventory', '$2a$10$e8w.M1n0Fek3/V2u1g5vQeLdZ9.e8tZ4g3wX3f5.c8J2k0N5m6O7q', 'Suresh Pillai', 'inventory@smartmfg.com', 'Warehouse & Inventory', 1),
(5, 'supervisor', '$2a$10$e8w.M1n0Fek3/V2u1g5vQeLdZ9.e8tZ4g3wX3f5.c8J2k0N5m6O7q', 'Neha Kapoor', 'supervisor@smartmfg.com', 'Plant Quality & Oversight', 1);

-- User Role Assignments
INSERT INTO `user_roles` (`user_id`, `role_id`) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5);

-- Customers
INSERT INTO `customers` (`id`, `customer_code`, `name`, `email`, `phone`, `company`, `address`, `active`) VALUES
(1, 'CUST-1001', 'Acme Industrial Corp', 'purchasing@acmeind.com', '+91 98200 11221', 'Acme Industrial Ltd', 'Plot 42, MIDC Industrial Area, Pune', 1),
(2, 'CUST-1002', 'Titan Aerospace Ltd', 'procure@titanaero.com', '+91 98101 22334', 'Titan Aerospace', 'Whitefield Tech Park, Bengaluru', 1),
(3, 'CUST-1003', 'Apex Robotics Pvt Ltd', 'orders@apexrobotics.in', '+91 98450 33445', 'Apex Robotics', 'Cyber City, Gurugram', 1),
(4, 'CUST-1004', 'Bharat Heavy Motors', 'supply@bhmotors.co.in', '+91 97660 44556', 'Bharat Motors Group', 'Pithampur Auto Cluster, Indore', 1),
(5, 'CUST-1005', 'Dynamic Hydraulics', 'contact@dynamichyd.com', '+91 98220 55667', 'Dynamic Power & Hydraulics', 'GIDC Estate, Vadodara', 1),
(6, 'CUST-1006', 'Zenith Electronics', 'purchase@zenithelec.com', '+91 99100 66778', 'Zenith Systems Ltd', 'Electronic City Phase 1, Bengaluru', 1),
(7, 'CUST-1007', 'Precision Gears & Axles', 'sales@precisiongears.in', '+91 98900 77889', 'Precision Engineering', 'Ambattur Industrial Estate, Chennai', 1),
(8, 'CUST-1008', 'Matrix Automated Plants', 'info@matrixplants.com', '+91 98300 88990', 'Matrix Solutions', 'Salt Lake Sector V, Kolkata', 1),
(9, 'CUST-1009', 'Omni Automation Tools', 'buy@omniauto.com', '+91 98720 99001', 'Omni Automation', 'Phase 8 Industrial Focal Point, Mohali', 1),
(10, 'CUST-1010', 'Quantum Mechatronics', 'orders@quantummech.in', '+91 98480 12345', 'Quantum Technologies', 'HITEC City, Hyderabad', 1);

-- Products
INSERT INTO `products` (`id`, `product_code`, `name`, `description`, `category`, `unit_price`, `production_duration_hours`, `min_stock_level`, `active`) VALUES
(1, 'PRD-R01', '6-Axis Industrial Robotic Arm', 'Heavy duty 20kg payload articulation arm', 'Robotics', 14500.00, 18, 5, 1),
(2, 'PRD-R02', 'Delta High-Speed Pick Robot', 'High-accuracy packaging delta mechanism', 'Robotics', 9800.00, 12, 4, 1),
(3, 'PRD-E01', 'PLC Master Controller Board', 'Industrial 32-channel I/O PLC logic processor', 'Electronics', 750.00, 6, 25, 1),
(4, 'PRD-E02', 'Optical Vision Inspection Sensor', 'Sub-millimeter edge quality detection unit', 'Electronics', 1250.00, 8, 15, 1),
(5, 'PRD-M01', 'Precision Planetary Gearbox 1:10', 'Zero-backlash robotic drive transmission', 'Mechanical', 1120.00, 10, 15, 1),
(6, 'PRD-M02', 'CNC Linear Ball Screw 1200mm', 'Hardened steel precision positioning screw', 'Mechanical', 480.00, 8, 20, 1),
(7, 'PRD-H01', 'High-Pressure Hydraulic Cylinder', '250 bar double acting stamping cylinder', 'Hydraulics', 1650.00, 14, 10, 1),
(8, 'PRD-A01', 'Braking Caliper Hydraulic Core', 'Automotive heavy transit disc caliper', 'Automotive', 620.00, 6, 25, 1);

-- Inventory
INSERT INTO `inventory` (`id`, `product_id`, `current_stock`, `allocated_stock`, `min_stock_level`) VALUES
(1, 1, 12, 2, 5),
(2, 2, 8, 1, 4),
(3, 3, 60, 10, 25),
(4, 4, 35, 5, 15),
(5, 5, 28, 4, 15),
(6, 6, 50, 6, 20),
(7, 7, 22, 3, 10),
(8, 8, 60, 4, 25);
