package com.smart.manufacturing.service.impl;

import com.smart.manufacturing.entity.*;
import com.smart.manufacturing.enums.OrderStatus;
import com.smart.manufacturing.enums.Priority;
import com.smart.manufacturing.enums.ProductionTaskStatus;
import com.smart.manufacturing.exception.OrderNotFoundException;
import com.smart.manufacturing.repository.ManufacturingOrderRepository;
import com.smart.manufacturing.repository.ProductionScheduleRepository;
import com.smart.manufacturing.repository.ProductionTaskRepository;
import com.smart.manufacturing.service.SchedulingService;
import com.smart.manufacturing.strategy.OrderSchedulingComparator;
import com.smart.manufacturing.strategy.PriorityStrategy;
import com.smart.manufacturing.strategy.PriorityStrategyFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.PriorityQueue;

@Service
@Transactional
public class SchedulingServiceImpl implements SchedulingService {

    private static final Logger log = LoggerFactory.getLogger(SchedulingServiceImpl.class);

    private final ManufacturingOrderRepository orderRepository;
    private final ProductionScheduleRepository scheduleRepository;
    private final ProductionTaskRepository taskRepository;
    private final PriorityStrategyFactory strategyFactory;

    @Autowired
    public SchedulingServiceImpl(ManufacturingOrderRepository orderRepository,
                                 ProductionScheduleRepository scheduleRepository,
                                 ProductionTaskRepository taskRepository,
                                 PriorityStrategyFactory strategyFactory) {
        this.orderRepository = orderRepository;
        this.scheduleRepository = scheduleRepository;
        this.taskRepository = taskRepository;
        this.strategyFactory = strategyFactory;
    }

    @Override
    public ProductionSchedule scheduleOrder(Long orderId, String username) {
        log.info("Generating production schedule and tasks for order ID: {}", orderId);
        ManufacturingOrder order = orderRepository.findById(orderId)
                .orElseThrow(() -> new OrderNotFoundException(orderId));

        // Create or get daily production schedule batch
        LocalDate scheduleDate = LocalDate.now();
        String scheduleCode = "SCHED-" + scheduleDate + "-" + order.getOrderNumber();
        ProductionSchedule schedule = scheduleRepository.findByScheduleCode(scheduleCode)
                .orElseGet(() -> {
                    ProductionSchedule newSchedule = new ProductionSchedule(
                            scheduleCode,
                            scheduleDate,
                            "Daily Schedule: " + order.getOrderNumber(),
                            "Automated schedule generated by " + (username != null ? username : "System")
                    );
                    return scheduleRepository.save(newSchedule);
                });

        PriorityStrategy strategy = strategyFactory.getStrategy(order.getPriority());
        LocalDateTime cursorTime = LocalDateTime.now().plusHours(1);

        int taskIndex = 1;
        for (OrderItem item : order.getItems()) {
            Product product = item.getProduct();
            int totalDurationHours = product.getProductionDurationHours() * item.getQuantity();

            // Calculate lead time days based on strategy (URGENT/HIGH compress shift lead times)
            int leadDays = strategy.calculateLeadTimeDays(totalDurationHours);
            LocalDateTime plannedStart = cursorTime;
            LocalDateTime plannedEnd = plannedStart.plusDays(leadDays).plusHours(totalDurationHours % 24);

            String taskCode = "TSK-" + order.getId() + "-" + taskIndex + "-" + product.getProductCode();
            String assignedTeam = determineProductionTeam(product.getCategory(), taskIndex);

            ProductionTask task = new ProductionTask(
                    taskCode,
                    order,
                    product,
                    item.getQuantity(),
                    assignedTeam,
                    order.getPriority(),
                    plannedStart,
                    plannedEnd
            );
            task.setSchedule(schedule);
            task.setNotes("Generated via " + strategy.getSchedulingPolicyDescription());

            taskRepository.save(task);
            schedule.addTask(task);
            order.addTask(task);

            // Shift cursor for sequential station routing
            cursorTime = plannedEnd.plusHours(2);
            taskIndex++;
        }

        return scheduleRepository.save(schedule);
    }

    @Override
    @Transactional(readOnly = true)
    public PriorityQueue<ManufacturingOrder> buildPrioritizedProductionQueue() {
        log.info("Building DSA PriorityQueue for active manufacturing orders");
        // Instantiate Java PriorityQueue with custom Comparator demonstrating DSA + Polymorphism
        PriorityQueue<ManufacturingOrder> queue = new PriorityQueue<>(new OrderSchedulingComparator(strategyFactory));

        // Fetch orders requiring scheduling or in active production
        List<ManufacturingOrder> candidates = orderRepository.findAll();
        for (ManufacturingOrder order : candidates) {
            if (order.getStatus() == OrderStatus.APPROVED ||
                order.getStatus() == OrderStatus.SCHEDULED ||
                order.getStatus() == OrderStatus.IN_PROGRESS) {
                queue.offer(order);
            }
        }

        return queue;
    }

    @Override
    @Transactional(readOnly = true)
    public List<ManufacturingOrder> getPrioritizedProductionQueueList() {
        // Poll through PriorityQueue to produce ordered List without altering persistence
        PriorityQueue<ManufacturingOrder> queue = buildPrioritizedProductionQueue();
        List<ManufacturingOrder> orderedList = new ArrayList<>();
        while (!queue.isEmpty()) {
            orderedList.add(queue.poll());
        }
        return orderedList;
    }

    @Override
    @Transactional(readOnly = true)
    public List<ProductionSchedule> getAllSchedules() {
        return scheduleRepository.findAllByOrderByScheduleDateDesc();
    }

    @Override
    @Transactional(readOnly = true)
    public ProductionSchedule getScheduleById(Long id) {
        return scheduleRepository.findById(id).orElse(null);
    }

    private String determineProductionTeam(String category, int index) {
        if (category == null) return "Production Line Alpha";
        return switch (category.toLowerCase()) {
            case "electronics" -> "SMT Surface Mount Line " + ((index % 2) + 1);
            case "mechanical", "automotive" -> "CNC Machining Cell " + ((index % 3) + 1);
            case "hydraulics" -> "High-Pressure Assembly Unit";
            case "sensors", "robotics" -> "Precision Micro-Assembly Line";
            default -> "Main Manufacturing Bay " + ((index % 4) + 1);
        };
    }
}
